export const S = {
  layout: { display: "flex", minHeight: "100vh", background: "var(--bg)" },
  sidebar: {
    width: 210,
    flexShrink: 0,
    background: "var(--s1)",
    borderRight: "1px solid var(--b1)",
    display: "flex",
    flexDirection: "column",
  },
  sidebarCollapsed: {
    width: 58,
    flexShrink: 0,
    background: "var(--s1)",
    borderRight: "1px solid var(--b1)",
    display: "flex",
    flexDirection: "column",
  },
  logo: {
    padding: "20px 18px 16px",
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: ".1em",
    textTransform: "uppercase",
    color: "var(--accent)",
    borderBottom: "1px solid var(--b1)",
  },
  logoCollapsed: {
    padding: "18px 0",
    fontSize: 18,
    textAlign: "center",
    color: "var(--accent)",
    borderBottom: "1px solid var(--b1)",
  },
  nav: { padding: "10px 8px", flex: 1 },
  navCollapsed: { padding: "8px 4px", flex: 1 },
  main: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    overflow: "hidden",
  },
  topbar: {
    background: "var(--s1)",
    borderBottom: "1px solid var(--b1)",
    padding: "13px 24px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    position: "sticky",
    top: 0,
    zIndex: 20,
  },
  content: { padding: "20px 24px", overflowY: "auto", flex: 1 },
  contentMobile: { padding: "16px 12px", overflowY: "auto", flex: 1, paddingBottom: 80 },
  card: {
    background: "var(--s1)",
    border: "1px solid var(--b1)",
    borderRadius: 10,
  },
  kpiGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill,minmax(180px,1fr))",
    gap: 12,
    marginBottom: 20,
  },
  kpiGridMobile: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: 8,
    marginBottom: 16,
  },
  filters: {
    display: "flex",
    gap: 8,
    marginBottom: 14,
    flexWrap: "wrap",
    alignItems: "center",
  },
  // Bottom nav for mobile
  bottomNav: {
    position: "fixed",
    bottom: 0,
    left: 0,
    right: 0,
    background: "var(--s1)",
    borderTop: "1px solid var(--b1)",
    display: "flex",
    zIndex: 50,
    height: 60,
  },
};